inherit_mode:
  merge:
    - Include

AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
    - "spec/support/examples/**/*" # Couldn't get it configured in spec/.rubocop.yml
  DisplayCopNames: true
  UseCache: true
  CacheRootDirectory: ./tmp
  NewCops: enable

Style/RescueStandardError:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: lambda

Style/WordArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/GuardClause:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
